### PR TITLE
Use GitHub Actions to validate CSVs

### PR DESCRIPTION
**Pull request by kmcelwee**
Currently, CSVs are tested one-by-one, we may want to create a pytest suite.

### CODE REVIEW

**Review by rlskoeser — CHANGES_REQUESTED** [review]
This seems like a reasonable starting point. 

Shouldn't the workflow filename be more specific? Maybe something like `ci/validate-csv` ? I don't know what kind of naming conventions there are for github actions.

Can we just run goodtables on all the CSV files, so we don't have to know ahead of time what CSV files exist? (i.e. `goodtables data/*.csv` )? 

I'd like to see the goodtables validation running against a datapackage / schema document in future, but we can add that in a subsequent revision.

Requested changes:
- rename the workflow file to something more specific/meaningful
- revise or remove the starter comments 
- run on all data files with either wildcard or configurable setting

**Comment by kmcelwee** [comment]
yes of course on all of those points 🤦🏻‍♂️

**Review by rlskoeser — APPROVED** [review]
Your updates look good to me, should we merge?

**Comment by kmcelwee** [comment]
Sidenote: "Validate CSVs" is now passing because it's not finding datapackage.json, surprisingly this defaults to "pass"

**Pull request merged**
